# Generated by Django 6.0.2 on 2026-02-20 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='smartguard_app.buildingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_label', models.CharField(max_length=100)),
                ('appliance_name', models.CharField(max_length=150)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='smartguard_app.building')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('power_watts', models.FloatField()),
                ('power_factor', models.FloatField(default=1.0)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='smartguard_app.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('SPIKE', 'Sudden Power Spike'), ('OVERLOAD', 'Prolonged Overloading'), ('ABNORMAL', 'Abnormal Consumption Pattern'), ('LOW_PF', 'Low Power Factor'), ('VOLTAGE_SAG', 'Voltage Sag'), ('VOLTAGE_SWELL', 'Voltage Swell')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='smartguard_app.energyreading')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='smartguard_app.sensor')),
            ],
            options={
                'verbose_name_plural': 'Anomalies',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ANOMALY', 'Anomaly Alert'), ('MAINTENANCE', 'Maintenance Reminder'), ('THRESHOLD', 'Threshold Exceeded'), ('SYSTEM', 'System Notification')], max_length=15)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('anomaly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='smartguard_app.anomaly')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='smartguard_app.building')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='smartguard_app.sensor')),
            ],
        ),
    ]
